services:
  api:
    build: ./backend
    volumes:
      - ./backend/app:/code/app
    environment:
      - MINIO_SERVER_HOST=minio
      - MINIO_SERVER_ACCESS_KEY=dev_user
      - MINIO_SERVER_SECRET_KEY=dev_pass
      - PATIENT_IMG_BUCKET=patient-images
      - PROXY_PREFIX_PATH=/api/v1
      - DB_NAME=ion
      - DB_HOST=mongodb
      - DB_USER=dev_user
      - DB_PASS=dev_pass
    ports:
      - 8080:80
    depends_on:
      - mongodb
      - minio
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=ion
    volumes:
      - /data/db
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=dev_user
      - MINIO_ROOT_PASSWORD=dev_pass
      - MINIO_DEFAULT_BUCKETS=patient-images
    volumes:
      - ./backend/minio_container_data_persistence:/bitnami/minio/data
  web:
    image: nginx:latest
    volumes:
      - ./backend/nginx_templates:/etc/nginx/templates
      - ./frontend:/usr/share/nginx/html
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - API_HOST=api
      - API_PORT=80
      - API_PREFIX_PATH=/api/v1
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - PATIENT_IMG_BUCKET=patient-images
    depends_on:
      - api
